apiVersion: v1
kind: ReplicationController
metadata:
  name: romano-test  
spec:
  replicas: 1
  template:  
    metadata:
      labels:
        app: romano-test
    spec:
      containers:
      - name: romano
        image: cajecasu/demodevco        
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: romano-svc
  labels:
    app: romano  
spec:  
  type: NodePort
  ports:
  - port: 3001
    nodePort: 30010
    protocol: TCP
    name: http
  selector:
    app:  romano-test